#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {
  checkProjectionSink,
  defineProjectionSpec,
  runProjectionSink,
} from "../lib/projection-sink.mjs";
import {
  apiSourceMode,
  sourceTsdocApiMarkdown,
  sourceTsdocModes,
  sourceTsdocRecordsForPackage,
  validateSourceTsdocRecords,
} from "../lib/public-api-model.mjs";
import { workspacePackagePaths } from "../lib/workspace-manifest.mjs";

const root = process.cwd();
const check = process.argv.includes("--check");
const surfacePath = path.join(root, "docs/surface.json");
const rootPackage = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const rawSurfaceText = fs.readFileSync(surfacePath, "utf8");
const rawSurface = JSON.parse(rawSurfaceText);
const releaseVersion = rootPackage.agentOsRelease?.version;
const releaseLine =
  typeof releaseVersion === "string" && /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/u.test(releaseVersion)
    ? `${releaseVersion.split(".").slice(0, 2).join(".")}.x`
    : undefined;
const hardCodedReleaseLinePattern = /\b\d+\.\d+\.x\b/u;

const expandReleaseTokens = (value) => {
  if (typeof value === "string") {
    return releaseLine === undefined ? value : value.replaceAll("{releaseLine}", releaseLine);
  }
  if (Array.isArray(value)) return value.map(expandReleaseTokens);
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [key, expandReleaseTokens(entry)]),
    );
  }
  return value;
};

const surface = expandReleaseTokens(rawSurface);

const generatedNotice = (source) =>
  `<!-- generated by packages/cli/src/generate/generate-docs.mjs; edit ${source} -->`;

const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

const docsSourceFacts = {
  kind: "source-set",
  ref: "docs.generate-docs.source-facts",
  sources: [
    { kind: "file", ref: "package.json" },
    { kind: "file", ref: "docs/surface.json" },
    { kind: "directory", ref: "docs/packages" },
    { kind: "directory", ref: "docs/api" },
    { kind: "tsdoc", ref: "exported public API TSDoc" },
  ],
};

const fileProjection = (file) =>
  defineProjectionSpec({
    id: `docs.generate-docs:${file}`,
    version: 1,
    source: docsSourceFacts,
    project: (text, ctx) => ctx.ok(`${text.replace(/\s+$/u, "")}\n`),
  });

const fileSink = (file) => {
  const target = path.join(root, file);
  return {
    id: file,
    read: () =>
      fs.existsSync(target)
        ? { _tag: "found", output: fs.readFileSync(target, "utf8") }
        : { _tag: "missing" },
    write: (output) => {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, output);
    },
    equals: (actual, expected) => actual === expected,
  };
};

const write = async (file, text) => {
  const spec = fileProjection(file);
  const sink = fileSink(file);
  if (check) {
    const result = await checkProjectionSink(spec, text, sink);
    if (result._tag === "projection_failed") {
      failures.push(`${file} projection failed: ${result.result.reason}`);
    } else if (result._tag === "stale") {
      failures.push(`${file} is stale`);
    }
    return;
  }

  const result = await runProjectionSink(spec, text, sink);
  if (result._tag === "projection_failed") {
    failures.push(`${file} projection failed: ${result.result.reason}`);
  }
};

const sectionBody = (text, heading) => {
  const marker = `## ${heading}`;
  const start = text.indexOf(marker);
  if (start === -1) throw new Error(`missing section ${heading}`);
  const after = text.slice(start + marker.length);
  const next = after.search(/^## /m);
  return (next === -1 ? after : after.slice(0, next)).trim();
};

const optionalSectionBody = (text, heading, fallback) => {
  const marker = `## ${heading}`;
  return text.includes(marker) ? sectionBody(text, heading) : fallback;
};

const pad = (value, width) => `${value}${" ".repeat(Math.max(0, width - value.length))}`;

const table = (headers, rows) => {
  const widths = headers.map((header, index) =>
    Math.max(header.length, ...rows.map((row) => row[index].length)),
  );
  const line = (row) => `| ${row.map((cell, index) => pad(cell, widths[index])).join(" | ")} |`;
  const divider = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
  return [line(headers), divider, ...rows.map(line)].join("\n");
};

const githubDocsBase = "https://github.com/yansircc/agentOS/blob/main/docs";

const rewriteDocsLinksForGithub = (text, sourceFile) =>
  text.replace(/\[([^\]\n]+)\]\(([^)\s]+)(\s+"[^"]*")?\)/gu, (full, label, href, title = "") => {
    if (!href.endsWith(".md") && !href.includes(".md#")) return full;
    const [rawPath, rawAnchor] = href.split("#");
    if (!rawPath.endsWith(".md")) return full;
    const sourceDir = path.posix.dirname(sourceFile);
    const target = path.posix.normalize(path.posix.join(sourceDir, rawPath));
    if (!target.startsWith("docs/")) return full;
    const anchor = rawAnchor === undefined ? "" : `#${rawAnchor}`;
    return `[${label}](${githubDocsBase}/${target.slice("docs/".length)}${anchor}${title})`;
  });

const replaceBlock = async (file, id, content) => {
  const source = read(file);
  const startMarker = `<!-- agentos:generated ${id}:start -->`;
  const endMarker = `<!-- agentos:generated ${id}:end -->`;
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`${file} missing generated block ${id}`);
  }
  const next = end + endMarker.length;
  await write(
    file,
    `${source.slice(0, start + startMarker.length)}\n\n${content}\n\n${source.slice(end, next)}${source.slice(next)}`,
  );
};

const packages = surface.packages;
const packagesByPath = new Map(packages.map((pkg) => [pkg.path, pkg]));
const failures = [];
const audienceKinds = new Map(Object.entries(surface.audienceKinds ?? {}));

if (releaseLine === undefined) {
  failures.push("package.json agentOsRelease.version must be a semver release source");
}

if (hardCodedReleaseLinePattern.test(rawSurfaceText)) {
  failures.push("docs/surface.json must use {releaseLine}; hard-coded release lines are forbidden");
}

for (const pkg of packages) {
  const packageJsonPath = path.join(root, pkg.path, "package.json");
  if (!fs.existsSync(packageJsonPath)) {
    failures.push(`${pkg.path}/package.json missing`);
    continue;
  }
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
  if (packageJson.name !== pkg.name) {
    failures.push(`${pkg.path}: package.json name ${packageJson.name} does not match ${pkg.name}`);
  }
}

if (audienceKinds.size === 0) {
  failures.push("docs/surface.json: audienceKinds must declare at least one audience kind");
}

const entrypointRowsForPackage = (pkg) => {
  const entrypoints = Array.isArray(pkg.entrypoints) ? pkg.entrypoints : [];
  return entrypoints.map((entry) => [
    `\`${pkg.name}${entry.subpath === "." ? "" : entry.subpath.slice(1)}\``,
    entry.audiences.map((audience) => `\`${audience}\``).join(", "),
    entry.capability,
  ]);
};

const validateEntrypointAudience = (pkg) => {
  const entrypoints = pkg.entrypoints;
  if (pkg.published !== true) return;
  if (!Array.isArray(entrypoints) || entrypoints.length === 0) {
    failures.push(`${pkg.name}: published package must declare entrypoint audiences`);
    return;
  }
  const seen = new Set();
  for (const entry of entrypoints) {
    const label = `${pkg.name}:${entry?.subpath ?? "entrypoint"}`;
    if (entry === null || typeof entry !== "object" || Array.isArray(entry)) {
      failures.push(`${label}: entrypoint must be an object`);
      continue;
    }
    if (entry.subpath !== "." && !/^\.\/[a-z0-9][a-z0-9./-]*$/u.test(entry.subpath)) {
      failures.push(`${label}: subpath must be "." or a package export subpath`);
      continue;
    }
    if (seen.has(entry.subpath)) {
      failures.push(`${label}: duplicate entrypoint audience declaration`);
    }
    seen.add(entry.subpath);
    if (!Array.isArray(entry.audiences) || entry.audiences.length === 0) {
      failures.push(`${label}: audiences must be a non-empty array`);
      continue;
    }
    for (const audience of entry.audiences) {
      if (!audienceKinds.has(audience)) {
        failures.push(`${label}: unknown audience kind ${audience}`);
      }
    }
    if (typeof entry.capability !== "string" || entry.capability.length === 0) {
      failures.push(`${label}: capability must be a non-empty string`);
    }
  }
};

for (const pkg of packages) validateEntrypointAudience(pkg);

for (const packagePath of workspacePackagePaths(root)) {
  const pkgPath = String(packagePath);
  if (!packagesByPath.has(pkgPath)) {
    failures.push(`${pkgPath} is missing from docs/surface.json`);
  }
}

for (const pkg of packages) {
  const packageDocPath = `docs/packages/${pkg.slug}.md`;
  const packageDoc = read(packageDocPath);
  const packageSection = (heading) =>
    rewriteDocsLinksForGithub(sectionBody(packageDoc, heading), packageDocPath);
  const readme = [
    generatedNotice(`docs/surface.json and ${packageDocPath}`),
    "",
    `# ${pkg.name}`,
    "",
    "## Purpose",
    "",
    packageSection("Purpose"),
    "",
    "## Public API Status",
    "",
    pkg.readmeStatus,
    "",
    "## Audience",
    "",
    entrypointRowsForPackage(pkg).length === 0
      ? "No published npm entrypoints."
      : table(["Entrypoint", "Audience", "Capability"], entrypointRowsForPackage(pkg)),
    "",
    "## Invariant",
    "",
    packageSection("Invariant"),
    "",
    "## Minimal Usage",
    "",
    packageSection("Minimal Usage"),
    "",
    "## Verification",
    "",
    packageSection("Verification"),
    "",
  ].join("\n");
  await write(`${pkg.path}/README.md`, readme);

  if (pkg.apiSource !== undefined) {
    const mode = apiSourceMode(pkg);
    if (sourceTsdocModes.has(mode)) {
      const records = sourceTsdocRecordsForPackage(root, pkg);
      failures.push(...validateSourceTsdocRecords(pkg, records));
      await write(pkg.apiSource, sourceTsdocApiMarkdown(pkg, records));
    } else if (mode !== "manual") {
      failures.push(`${pkg.name}: unsupported apiSourceMode ${mode}`);
    }

    const apiDoc = read(pkg.apiSource);
    const publicApiSource = sourceTsdocModes.has(mode)
      ? `docs/surface.json and exported TSDoc in ${pkg.path}/src`
      : `docs/surface.json and ${pkg.apiSource}`;
    const publicApi = [
      generatedNotice(publicApiSource),
      "",
      `# ${pkg.name} Public API`,
      "",
      `Status: ${pkg.apiStatus}`,
      "",
      "## Public exports",
      "",
      sectionBody(apiDoc, "Public exports"),
      "",
      "## Experimental exports",
      "",
      sectionBody(apiDoc, "Experimental exports"),
      "",
      "## Deprecated exports",
      "",
      optionalSectionBody(apiDoc, "Deprecated exports", "None."),
      "",
      "## Internal-only exports",
      "",
      sectionBody(apiDoc, "Internal-only exports"),
      "",
    ].join("\n");
    await write(`${pkg.path}/PUBLIC_API.md`, publicApi);
  }
}

const primaryPackages = packages.filter((pkg) => pkg.primary === true);
const releasePosture = `Current release posture: ${surface.release.line} ${surface.release.posture}. ${surface.release.publicApiMeaning}`;

await replaceBlock("README.md", "release-posture", releasePosture);

const rootPackageMap = table(
  ["Package", "Role"],
  primaryPackages.map((pkg) => [`\`${pkg.name}\``, pkg.role]),
);

await replaceBlock("README.md", "package-map", rootPackageMap);

const runtimePackageMap = table(
  ["Package", "Published", "Status", "Boundary"],
  packages.map((pkg) => [
    `\`${pkg.name}\``,
    pkg.published === true ? "yes" : "no",
    pkg.status,
    pkg.boundary,
  ]),
);

await replaceBlock("docs/runtime-packages.md", "runtime-package-map", runtimePackageMap);

const audienceKindMap = table(
  ["Audience", "Meaning"],
  [...audienceKinds.entries()].map(([audience, meaning]) => [`\`${audience}\``, meaning]),
);

await replaceBlock("docs/runtime-packages.md", "audience-kinds", audienceKindMap);

const entrypointAudienceMap = table(
  ["Entrypoint", "Audience", "Capability"],
  packages.flatMap(entrypointRowsForPackage),
);

await replaceBlock("docs/runtime-packages.md", "entrypoint-audience-map", entrypointAudienceMap);

await replaceBlock(
  "docs/runtime-packages.md",
  "holds",
  surface.holds.map((hold) => hold.text).join("\n\n"),
);

const skillPackageMap = table(
  ["Need", "Package"],
  primaryPackages.map((pkg) => [pkg.need, `\`${pkg.name}\``]),
);

await replaceBlock("skills/agentos/references/package-map.md", "package-map", skillPackageMap);

if (failures.length > 0) {
  console.error(failures.join("\n"));
  process.exit(1);
}

if (check) {
  console.log("generated docs are current");
} else {
  console.log("generated docs updated");
}
