export type AgentOsSourceAliasSpec = readonly [specifier: string, sourcePath: string];
export const agentOsSourceAliasSpecs = [
  ["@agent-os/core", "packages/core/src/index.ts"],
  ["@agent-os/core/abort", "packages/core/src/abort.ts"],
  ["@agent-os/core/agent-schema", "packages/core/src/agent-schema.ts"],
  ["@agent-os/core/authored-value", "packages/core/src/authored-value.ts"],
  ["@agent-os/core/backend-protocol", "packages/core/src/backend-protocol/index.ts"],
  [
    "@agent-os/core/backend-protocol/reference",
    "packages/core/src/backend-protocol/reference/index.ts",
  ],
  ["@agent-os/core/boundary-contract", "packages/core/src/boundary-contract.ts"],
  ["@agent-os/core/carrier", "packages/core/src/carrier.ts"],
  ["@agent-os/core/context", "packages/core/src/context.ts"],
  ["@agent-os/core/effect-claim", "packages/core/src/effect-claim.ts"],
  ["@agent-os/core/errors", "packages/core/src/errors.ts"],
  ["@agent-os/core/extensions", "packages/core/src/extensions.ts"],
  ["@agent-os/core/live-edge", "packages/core/src/live-edge.ts"],
  ["@agent-os/core/llm-protocol", "packages/core/src/llm-protocol/index.ts"],
  ["@agent-os/core/material-ref", "packages/core/src/material-ref.ts"],
  ["@agent-os/core/projection", "packages/core/src/projection.ts"],
  ["@agent-os/core/quota", "packages/core/src/quota.ts"],
  ["@agent-os/core/recorded-value", "packages/core/src/recorded-value.ts"],
  ["@agent-os/core/ref-resolver", "packages/core/src/ref-resolver.ts"],
  ["@agent-os/core/runtime-protocol", "packages/core/src/runtime-protocol/index.ts"],
  ["@agent-os/core/runtime-scope", "packages/core/src/runtime-scope.ts"],
  ["@agent-os/core/settlement-contract", "packages/core/src/settlement-contract.ts"],
  ["@agent-os/core/telemetry-protocol", "packages/core/src/telemetry-protocol/index.ts"],
  ["@agent-os/core/tools", "packages/core/src/tools.ts"],
  ["@agent-os/core/types", "packages/core/src/types.ts"],
  ["@agent-os/runtime", "packages/runtime/src/index.ts"],
  ["@agent-os/runtime/admission", "packages/runtime/src/admission.ts"],
  ["@agent-os/runtime/cloudflare", "packages/runtime/src/cloudflare/index.ts"],
  ["@agent-os/runtime/cloudflare/do-rpc", "packages/runtime/src/cloudflare/do-rpc.ts"],
  ["@agent-os/runtime/cloudflare/ops-api", "packages/runtime/src/cloudflare/ops-api/index.ts"],
  ["@agent-os/runtime/in-memory", "packages/runtime/src/in-memory/index.ts"],
  ["@agent-os/runtime/llm-effect-ai", "packages/runtime/src/llm-effect-ai/index.ts"],
  ["@agent-os/runtime/node", "packages/runtime/src/node/index.ts"],
  ["@agent-os/runtime/run-projector", "packages/runtime/src/run-projector.ts"],
  ["@agent-os/runtime/telemetry-otlp", "packages/runtime/src/telemetry-otlp/index.ts"],
  ["@agent-os/decision-gate", "packages/carriers/decision-gate/src/index.ts"],
  ["@agent-os/deploy", "packages/carriers/deploy/src/index.ts"],
  ["@agent-os/git-carrier", "packages/carriers/git/src/index.ts"],
  ["@agent-os/image", "packages/carriers/image/src/index.ts"],
  ["@agent-os/resource-carrier", "packages/carriers/resource/src/index.ts"],
  ["@agent-os/sandbox", "packages/execution-domains/sandbox/src/index.ts"],
  ["@agent-os/staging-artifact", "packages/carriers/staging-artifact/src/index.ts"],
  ["@agent-os/tenant-material", "packages/providers/tenant-material/src/index.ts"],
  ["@agent-os/verification", "packages/carriers/verification/src/index.ts"],
  ["@agent-os/workspace-job", "packages/carriers/workspace-job/src/index.ts"],
  ["@agent-os/workspace-op", "packages/carriers/workspace-op/src/index.ts"],
  ["@agent-os/workspace-session", "packages/carriers/workspace-session/src/index.ts"],
  ["@agent-os/agent-authoring", "packages/composers/agent-authoring/src/index.ts"],
  ["@agent-os/config", "packages/composers/config/src/index.ts"],
  ["@agent-os/config/schema.json", "packages/composers/config/schema.json"],
  ["@agent-os/attached-stream", "packages/composers/attached-stream/src/index.ts"],
  ["@agent-os/workspace-agent", "packages/composers/workspace-agent/src/index.ts"],
  ["@agent-os/ag-ui", "packages/wire-adapters/ag-ui/src/index.ts"],
  ["@agent-os/client", "packages/client/src/index.ts"],
  ["@agent-os/client/react", "packages/client/src/react/index.ts"],
  ["@agent-os/client/svelte", "packages/client/src/svelte/index.ts"],
  ["@agent-os/run-stream", "packages/composers/run-stream/src/index.ts"],
  ["@agent-os/workspace-binding", "packages/composers/workspace-binding/src/index.ts"],
  ["@agent-os/sse-http", "packages/transports/sse-http/src/index.ts"],
  ["@agent-os/turn-stream", "packages/composers/turn-stream/src/index.ts"],
  ["@agent-os/workspace-env", "packages/execution-domains/workspace-env/src/index.ts"],
  ["@agent-os/deploy-cloudflare", "packages/providers/deploy-cloudflare/src/index.ts"],
  ["@agent-os/dynamic-worker", "packages/providers/dynamic-worker/src/index.ts"],
  ["@agent-os/llm-transport-http", "packages/providers/llm-transport-http/src/index.ts"],
  [
    "@agent-os/image-resource-settlement",
    "packages/providers/image-resource-settlement/src/index.ts",
  ],
  ["@agent-os/resource-cloudflare", "packages/providers/resource-cloudflare/src/index.ts"],
  ["@agent-os/workspace-op-local", "packages/providers/workspace-op-local/src/index.ts"],
  ["@agent-os/sandbox-cloudflare", "packages/execution-domains/sandbox-cloudflare/src/index.ts"],
  [
    "@agent-os/workspace-env-cloudflare",
    "packages/execution-domains/workspace-env-cloudflare/src/index.ts",
  ],
  ["@agent-os/workspace-env-local", "packages/execution-domains/workspace-env-local/src/index.ts"],
  [
    "@agent-os/workspace-session-cloudflare",
    "packages/providers/workspace-session-cloudflare/src/index.ts",
  ],
] as const satisfies readonly AgentOsSourceAliasSpec[];

const repoRoot = new URL("../../", (import.meta as { readonly url: string }).url);

export const agentOsSourceAliases = (): Record<string, string> =>
  Object.fromEntries(
    [...agentOsSourceAliasSpecs]
      .sort(([left], [right]) => right.length - left.length || left.localeCompare(right))
      .map(([specifier, sourcePath]) => [specifier, new URL(sourcePath, repoRoot).pathname]),
  );
