export {
  WORKSPACE_AGENT_COMMAND,
  WORKSPACE_AGENT_PROJECTION,
  WORKSPACE_AGENT_PROJECTION_SCHEMA,
  defineWorkspaceAgentMount,
  isWorkspaceAgentCommandName,
  isWorkspaceAgentProjectionName,
} from "@agent-os/core/workspace-agent";
export type {
  WorkspaceAgentCommandInputByName,
  WorkspaceAgentCommandName,
  WorkspaceAgentCommandOutputByName,
  WorkspaceAgentCustomCommandInput,
  WorkspaceAgentDestroyCommandInput,
  WorkspaceAgentDriverMount,
  WorkspaceAgentFileEntry,
  WorkspaceAgentFilesProjection,
  WorkspaceAgentFilesProjectionShape,
  WorkspaceAgentGeneratedMount,
  WorkspaceAgentMutationCommandOutput,
  WorkspaceAgentProjectionName,
  WorkspaceAgentProjectionRead,
  WorkspaceAgentProjectionSchema,
  WorkspaceAgentProjectionSink,
  WorkspaceAgentProjectionValueByName,
  WorkspaceAgentReadFileCommandInput,
  WorkspaceAgentReadFileCommandOutput,
  WorkspaceAgentReadStateCommandInput,
  WorkspaceAgentReadStateCommandOutput,
  WorkspaceAgentResetCommandInput,
  WorkspaceAgentResumeInputRequestCommandInput,
  WorkspaceAgentStateProjection,
  WorkspaceAgentStateProjectionShape,
  WorkspaceAgentSubmitCommandInput,
} from "@agent-os/core/workspace-agent";
