#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const check = process.argv.includes("--check");
const surfacePath = path.join(root, "docs/surface.json");
const surface = JSON.parse(fs.readFileSync(surfacePath, "utf8"));

const generatedNotice = (source) =>
  `<!-- generated by scripts/generate-docs.mjs; edit ${source} -->`;

const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const write = (file, text) => {
  const target = path.join(root, file);
  const expected = `${text.replace(/\s+$/u, "")}\n`;
  if (check) {
    const actual = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
    if (actual !== expected) {
      failures.push(`${file} is stale`);
    }
    return;
  }
  fs.writeFileSync(target, expected);
};

const sectionBody = (text, heading) => {
  const marker = `## ${heading}`;
  const start = text.indexOf(marker);
  if (start === -1) throw new Error(`missing section ${heading}`);
  const after = text.slice(start + marker.length);
  const next = after.search(/^## /m);
  return (next === -1 ? after : after.slice(0, next)).trim();
};

const pad = (value, width) => `${value}${" ".repeat(Math.max(0, width - value.length))}`;

const table = (headers, rows) => {
  const widths = headers.map((header, index) =>
    Math.max(header.length, ...rows.map((row) => row[index].length)),
  );
  const line = (row) => `| ${row.map((cell, index) => pad(cell, widths[index])).join(" | ")} |`;
  const divider = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
  return [line(headers), divider, ...rows.map(line)].join("\n");
};

const replaceBlock = (file, id, content) => {
  const source = read(file);
  const startMarker = `<!-- agentos:generated ${id}:start -->`;
  const endMarker = `<!-- agentos:generated ${id}:end -->`;
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`${file} missing generated block ${id}`);
  }
  const next = end + endMarker.length;
  write(
    file,
    `${source.slice(0, start + startMarker.length)}\n\n${content}\n\n${source.slice(end, next)}${source.slice(next)}`,
  );
};

const packages = surface.packages;
const packagesByPath = new Map(packages.map((pkg) => [pkg.path, pkg]));
const failures = [];

const workspacePackagePaths = () => {
  const rootPackage = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
  const workspaces = Array.isArray(rootPackage.workspaces)
    ? rootPackage.workspaces
    : Array.isArray(rootPackage.workspaces?.packages)
      ? rootPackage.workspaces.packages
      : [];
  const paths = new Set();

  for (const workspace of workspaces) {
    if (typeof workspace !== "string") continue;
    if (workspace.endsWith("/*")) {
      const base = workspace.slice(0, -2);
      const baseDir = path.join(root, base);
      if (!fs.existsSync(baseDir)) continue;
      for (const entry of fs.readdirSync(baseDir, { withFileTypes: true })) {
        if (!entry.isDirectory()) continue;
        const packagePath = `${base}/${entry.name}`;
        if (fs.existsSync(path.join(root, packagePath, "package.json"))) {
          paths.add(packagePath);
        }
      }
      continue;
    }

    if (fs.existsSync(path.join(root, workspace, "package.json"))) {
      paths.add(workspace);
    }
  }

  return [...paths].sort((left, right) => left.localeCompare(right));
};

for (const pkg of packages) {
  const packageJsonPath = path.join(root, pkg.path, "package.json");
  if (!fs.existsSync(packageJsonPath)) {
    failures.push(`${pkg.path}/package.json missing`);
    continue;
  }
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
  if (packageJson.name !== pkg.name) {
    failures.push(`${pkg.path}: package.json name ${packageJson.name} does not match ${pkg.name}`);
  }
}

for (const pkgPath of workspacePackagePaths()) {
  if (!packagesByPath.has(pkgPath)) {
    failures.push(`${pkgPath} is missing from docs/surface.json`);
  }
}

for (const pkg of packages) {
  const packageDocPath = `docs/packages/${pkg.slug}.md`;
  const packageDoc = read(packageDocPath);
  const readme = [
    generatedNotice(`docs/surface.json and ${packageDocPath}`),
    "",
    `# ${pkg.name}`,
    "",
    "## Purpose",
    "",
    sectionBody(packageDoc, "Purpose"),
    "",
    "## Public API Status",
    "",
    pkg.readmeStatus,
    "",
    "## Invariant",
    "",
    sectionBody(packageDoc, "Invariant"),
    "",
    "## Minimal Usage",
    "",
    sectionBody(packageDoc, "Minimal Usage"),
    "",
    "## Verification",
    "",
    sectionBody(packageDoc, "Verification"),
    "",
  ].join("\n");
  write(`${pkg.path}/README.md`, readme);

  if (pkg.apiSource !== undefined) {
    const apiDoc = read(pkg.apiSource);
    const publicApi = [
      generatedNotice(`docs/surface.json and ${pkg.apiSource}`),
      "",
      `# ${pkg.name} Public API`,
      "",
      `Status: ${pkg.apiStatus}`,
      "",
      "## Public exports",
      "",
      sectionBody(apiDoc, "Public exports"),
      "",
      "## Experimental exports",
      "",
      sectionBody(apiDoc, "Experimental exports"),
      "",
      "## Internal-only exports",
      "",
      sectionBody(apiDoc, "Internal-only exports"),
      "",
    ].join("\n");
    write(`${pkg.path}/PUBLIC_API.md`, publicApi);
  }
}

const primaryPackages = packages.filter((pkg) => pkg.primary === true);
const releasePosture = `Current release posture: ${surface.release.line} ${surface.release.posture}. ${surface.release.publicApiMeaning}`;

replaceBlock("README.md", "release-posture", releasePosture);

const rootPackageMap = table(
  ["Package", "Role"],
  primaryPackages.map((pkg) => [`\`${pkg.name}\``, pkg.role]),
);

replaceBlock("README.md", "package-map", rootPackageMap);

const runtimePackageMap = table(
  ["Package", "Status", "Boundary"],
  packages.map((pkg) => [`\`${pkg.name}\``, pkg.status, pkg.boundary]),
);

replaceBlock("docs/runtime-packages.md", "runtime-package-map", runtimePackageMap);

replaceBlock(
  "docs/runtime-packages.md",
  "holds",
  surface.holds.map((hold) => hold.text).join("\n\n"),
);

const skillPackageMap = table(
  ["Need", "Package"],
  primaryPackages.map((pkg) => [pkg.need, `\`${pkg.name}\``]),
);

replaceBlock("skills/agentos/references/package-map.md", "package-map", skillPackageMap);

if (failures.length > 0) {
  console.error(failures.join("\n"));
  process.exit(1);
}

if (check) {
  console.log("generated docs are current");
} else {
  console.log("generated docs updated");
}
